source 'https://rubygems.org'

ruby '2.2.3'

gem 'aws-sdk'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'bootstrap3-datetimepicker-rails'
gem 'coffee-rails'
gem 'dalli'
gem 'font-awesome-sass'
gem 'jbuilder'
gem 'jekyll'
gem 'jquery-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'momentjs-rails'
gem 'pg'
gem 'puma'
gem 'rack-timeout'
gem 'rails'
gem 'redcarpet'
gem 'rouge'
gem 'rugged'
gem 'safe_yaml'
gem 'sanitize'
gem 'sass-rails'
gem 'sidekiq'
gem 'slim-rails'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'spring'
end

