development:
  adapter: postgresql
  database: static_website_manager_development
  encoding: unicode
  pool: 5
test:
  adapter: postgresql
  database: static_website_manager_test
  encoding: unicode
  pool: 5
