default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  database: postgres
  username: postgres
  pool: 32
development:
  <<: *default
test:
  <<: *default
  database: postgres_test
production:
  <<: *default
