default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: postgres
development:
  <<: *default
  database: static_website_manager_development
test:
  <<: *default
  database: static_website_manager_test
production:
  <<: *default
  database: static_website_manager_production
